# docker build -f src/main/docker/Dockerfile.jvm -t springboot/service-jvm .
# docker run -p 8081:8080 springboot/service

FROM registry.access.redhat.com/ubi8/openjdk-17:1.14

ARG JAR_FILE=../../../build/libs/*.jar
#ARG JAR_FILE=../../../build/libs/*-SNAPSHOT.jar
COPY ${JAR_FILE} /app.jar

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app.jar"]