version: '3.2'
services:
  service-quarkus-jvm:
    image: quarkus/service-jvm
    container_name: service-quarkus-jvm
    expose:
      - 8080
    ports:
      - 8081:8080
    networks:
      - monitoring
  service-springboot-jvm:
    image: springboot/service-jvm
    container_name: service-springboot-jvm
    expose:
      - 8080
    ports:
      - 8082:8080
    networks:
      - monitoring
  service-quarkus-native:
    image: quarkus/service-micro
    container_name: service-quarkus-native
    expose:
      - 8080
    ports:
      - 8083:8080
    networks:
      - monitoring
  service-springboot-native:
    image: service:0.0.1-SNAPSHOT
    container_name: service-springboot-native
    expose:
      - 8080
    ports:
      - 8084:8080
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:4.6.2
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:v2.0.0
    container_name: prometheus
    volumes:
      - ./docker/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro # <--- new volume
      - /mnt/windows_docker/:/rootfs/var/lib/docker:ro # <--- new volume
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - monitoring
    depends_on:
      - service-quarkus-jvm
      - service-springboot-jvm
      - service-quarkus-native
      - service-springboot-native
volumes:
  grafana-data: {}
  prometheus-data: {}
networks:
  monitoring:
    driver: bridge