---

apiVersion: v1

kind: Service

metadata:

  name: cadvisor-service
  
  labels: 
    app: cadvisor-app

spec:

  type: LoadBalancer

  selector:

    app: cadvisor-app

  ports:
 
    - port: 8080
    
      targetPort: 8080