---

 apiVersion: v1

 kind: Pod

 metadata:

   name: grafana-pod
   
   labels: 
    app: grafana-app

 spec:

   containers:

        - args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --storage.tsdb.retention=200h
          image: grafana/grafana:4.6.2
          name: grafana
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
   volumes:
        - name: grafana-data
          hostPath:
            path: grafana-data