---

 apiVersion: v1

 kind: Pod

 metadata:

   name: service-quarkus-native-pod
   
   labels: 
    app: service-quarkus-native-app

 spec:

   containers:

     - imagePullPolicy: Never
       
       name: service-quarkus-native

       image: quarkus/service-micro

       ports:

         - containerPort: 8080