---

apiVersion: v1

kind: Service

metadata:

  name: service-springboot-jvm-service
  
  labels: 
    app: service-springboot-jvm-app

spec:

  type: LoadBalancer

  selector:

    app: service-springboot-jvm-app

  ports:
 
    - port: 8082
    
      targetPort: 8080