---

apiVersion: v1

kind: Service

metadata:

  name: service-quarkus-jvm-service
  
  labels: 
    app: service-quarkus-jvm-app

spec:

  type: LoadBalancer

  selector:

    app: service-quarkus-jvm-app

  ports:
 
    - port: 8081
    
      targetPort: 8080