---

apiVersion: v1

kind: Service

metadata:

  name: service-springboot-native-service
  
  labels: 
    app: service-springboot-native-app

spec:

  type: LoadBalancer

  selector:

    app: service-springboot-native-app

  ports:
 
    - port: 8084
    
      targetPort: 8080