global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docker-host-alpha'

rule_files:
  - "targets.rules"
  - "host.rules"
  - "containers.rules"

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'service-quarkus-jvm'
    metrics_path: '/q/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['service-quarkus-jvm:8080']
 
  - job_name: 'service-springboot-jvm'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['service-springboot-jvm:8080']
      
  - job_name: 'service-quarkus-native'
    metrics_path: '/q/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['service-quarkus-native:8080']
 
  - job_name: 'service-springboot-native'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['service-springboot-native:8080']